import { Platform, StyleSheet } from "react-native"
import {
  brandColors,
  brandComponentTokens,
  brandMediaBackdrop,
  brandOnDangerSurface,
  brandRadius,
  brandSemanticColors,
  brandShadow,
  brandTranslucentPanel,
  brandTypography,
} from "../../app/brand-tokens"

export const parcelStyles = StyleSheet.create({
  parcelHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  selectionCountPill: {
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: brandColors.forest,
    backgroundColor: brandColors.successSoft,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  selectionCountPillText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  mapFrame: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandColors.canvas,
  },
  mapOverlayActions: {
    ...StyleSheet.absoluteFill,
    justifyContent: "flex-start",
    alignItems: "flex-end",
    padding: 12,
  },
  mapOverlayButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: brandSemanticColors.heroBorderStrongOnDark,
    backgroundColor: brandSemanticColors.heroScrimOnDark,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mapOverlayButtonText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  map: {
    width: "100%",
    height: 408,
  },
  mapHelperText: {
    ...brandTypography.meta,
    color: brandColors.textSecondary,
  },
  selectionSummaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  selectionPill: {
    borderRadius: brandRadius.pill,
    backgroundColor: brandColors.successSoft,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  selectionPillText: {
    ...brandTypography.meta,
    color: brandColors.forest,
  },
  fullscreenMapScreen: {
    flex: 1,
    backgroundColor: brandMediaBackdrop,
  },
  fullscreenMap: {
    flex: 1,
  },
  fullscreenMapOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 24,
  },
  fullscreenMapTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandTranslucentPanel.default,
    paddingHorizontal: 12,
    paddingVertical: Platform.select({ ios: 6, default: 10 }),
  },
  fullscreenMapTopTitle: {
    flex: 1,
    textAlign: "center",
    ...brandTypography.label,
    color: brandColors.forest,
  },
  fullscreenMapCloseButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: brandRadius.pill,
    borderWidth: 1,
    borderColor: brandSemanticColors.heroBorderStrongOnDark,
    backgroundColor: brandSemanticColors.heroScrimOnDark,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  fullscreenMapCloseText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  fullscreenMapFloatingActions: {
    alignSelf: "flex-end",
  },
  fullscreenMapActionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: brandColors.sage,
    backgroundColor: brandColors.forest,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: brandRadius.pill,
    ...brandShadow.card,
  },
  fullscreenMapActionButtonText: {
    ...brandTypography.meta,
    color: brandColors.white,
  },
  fullscreenMapBottomArea: {
    gap: 12,
  },
  fullscreenMapBottomSheet: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: brandColors.divider,
    backgroundColor: brandTranslucentPanel.strong,
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 8,
    ...brandShadow.card,
  },
  fullscreenMapBottomTitle: {
    ...brandTypography.sectionTitle,
    fontSize: 20,
    lineHeight: 24,
    color: brandColors.forest,
  },
  fullscreenMapBottomMeta: {
    ...brandTypography.sectionBody,
    fontSize: 13,
    lineHeight: 18,
    color: brandColors.textSecondary,
  },
  fullscreenMapBottomHint: {
    ...brandTypography.meta,
    color: brandColors.textSecondary,
  },
  fullscreenMapWarningCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: brandComponentTokens.notice.dangerBorder,
    backgroundColor: brandColors.errorSoft,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  fullscreenMapWarningText: {
    flex: 1,
    ...brandTypography.meta,
    color: brandOnDangerSurface,
  },
})
